
#' ---
#' title: "Choice of Datasets - Without Paper Countries"
#' author: "Ylva Matejko"
#' date: "Mar 05, 2026"
#' ---

#' The purpose of this script is to determine the choice of subset of the TIMSS 2023 data to be used in the present study. Out of the four datasets, the one with 
#' the largest discrepancies between participating countries will be chosen.
#' 
#' First, countries that did not participate in the digital assessment of TIMSS 2023 are removed from the dataset. Second, some items are temporarily recoded and cases with unit 
#' non-response are removed to simplify the process of choosing a subset. Then, the script divides the two full datasets generated by the IEA IDB Data Analyzer
#' on 4th and 8th grade students' TIMSS 2023 data into four datasets by grade and subject field.
#' 
#' To determine the choice of a subset for the analyses of the present study, a special function was designed. It gives back a table binding the country codes 
#' and the respective coded category percentages together. This function is applied to each of the prepared TIMSS 2023 subsets. The heads and tails, as well as the 
#' standard deviations of the Omitted / Invalid Response Category are investigated.
#' 
#' The omission statistics computed here are reported in Chapter 2.2.1 of my thesis.
#' 
#'------------------------------------------------------------------------------
#'
#' ### Load both grades' data

load(file = paste0(getwd(),"/YZM-Thesis/Data/GRADE4DATA_ORIG.Rdata"))
grade4data <- GRADE4DATA_ORIG

load(file = paste0(getwd(),"/YZM-Thesis/Data/GRADE8DATA_ORIG.Rdata"))
grade8data <- GRADE8DATA_ORIG

#'------------------------------------------------------------------------------
#'
#' ### Exclude paper countries
#' 
#' In grade 4, six countries administered the assessment in paper format, whereas in grade 8 this applied to 
#' four countries (Fishbein, 2025). These countries were omitted in the preliminary analyses as well as all further analyses in the present study. 

g4_paper_countries <- c(100, 196, 364, 414, 504, 710) # Bulgaria, Cyprus, Iran, Kuwait, Morocco, and South Africa
grade4data <- grade4data[!grade4data$IDCNTRY %in% g4_paper_countries,]

g8_paper_countries <- c(384, 364, 414, 710) # Ivory Coast, Iran, Kuwait, and South Africa
grade8data <- grade8data[!grade8data$IDCNTRY %in% g8_paper_countries,]


#'------------------------------------------------------------------------------
#'
#' ### Recode items with 6 response options raw data files
#' 
#' There are some items with 6 response options (A-F). The number 6 in the datasets as they are now can thus stand for "F" as well as "not reached". In the items 
#' with 6 response options, 69 is the code for "not reached". To avoid confusion in the analyse_missings function below, the respective items are recoded here. 
#' Since the only purpose of this script is determining the choice of subsets, and the subsets created here will not be used in parameter or ability estimation, 
#' all 6's on these items will be simply set to 5, so they count as "valid responses" in the analyse_missings function.
#' The items affected by this issue were identified through the TIMSS 2023 scoring scripts provided by Fishbein et al. (2025).

g4_six_options <- c('SE81048E', 'SE81048D', 'SE81048B','SE81048C','SE81048A')
grade4data[g4_six_options] <- lapply(grade4data[g4_six_options], function(x) ifelse(x == 6, 5, x))


g8_six_options <- c('SE72403B', 'SE82002E', 'SE72033D', 'SE72905C','SE82021A', 'SE82001D', 'SE72000C', 
                    'SE82002A', 'SE72033A', 'SE72905A', 'SE82021C', 'SE82001B', 'SE72000B', 'SE82002C', 
                    'SE72033E', 'SE72905D', 'SE72403A', 'SQ72S13A', 'SE82021D', 'SE82001A', 'SE72000E', 
                    'SE72403D', 'SE82001C', 'SE72000A', 'SE82002D', 'SE72033B', 'SE72905B', 'SE72403C', 
                    'SE82021B', 'SE82001E', 'SE72000D', 'SE82002B', 'SE72033C')

grade8data[g8_six_options] <- lapply(grade8data[g8_six_options], function(x) ifelse(x == 6, 5, x))


#'------------------------------------------------------------------------------
#'
#' ### Filter for Math and Science items
#'
#' Divide datasets in subsets for Math and Science for each grade.

df1 <- grade4data[,grep(pattern="^M", x=colnames(grade4data))] # store only math item responses in df1
df1$IDCNTRY <- grade4data$IDCNTRY # add country IDs to df1

df2 <- grade8data[,grep(pattern="^M", x=colnames(grade8data))] # store only data item responses in df2
df2$IDCNTRY <- grade8data$IDCNTRY # add country IDs to df2

df3 <- grade4data[,grep(pattern="^S", x=colnames(grade4data))] # store only datance item responses in df3
df3$IDCNTRY <- grade4data$IDCNTRY # add country IDs to df3

df4 <- grade8data[,grep(pattern="^S", x=colnames(grade8data))] # store only datance item responses in df4
df4$IDCNTRY <- grade8data$IDCNTRY # add country IDs to df4

#' Filter out nonresponse indicators

df1_nonresponse_indicators <- colnames(df1)[grep(pattern="^ME.1[A-Z]{3}(NEN)?$", x=colnames(df1))]
df1 <- df1[,!colnames(df1) %in% df1_nonresponse_indicators]

df2_nonresponse_indicators <- colnames(df2)[grep(pattern="^SE.1[A-Z]{3}(NEN)?$", x=colnames(df2))]
df2 <- df2[,!colnames(df2) %in% df2_nonresponse_indicators]

df3_nonresponse_indicators <- colnames(df3)[grep(pattern="^ME.2[A-Z]{3}(NEN)?$", x=colnames(df3))]
df3 <- df3[,!colnames(df3) %in% df3_nonresponse_indicators]

df4_nonresponse_indicators <- colnames(df4)[grep(pattern="^SE.2[A-Z]{3}(NEN)?$", x=colnames(df4))]
df4 <- df4[,!colnames(df4) %in% df4_nonresponse_indicators]

#' Filter out paper items

df1 <- df1[, !grepl("^SP", colnames(df1))]
df2 <- df2[, !grepl("^SP", colnames(df2))]
df3 <- df3[, !grepl("^SP", colnames(df3))]
df4 <- df4[, !grepl("^SP", colnames(df4))]

#'------------------------------------------------------------------------------
#'
#'### Analysis of the subsets
#'
#'This section analyses the item omission and not-reached rates using the function analyse_missings.

analyse_missings <- readRDS("YZM-Thesis/Objects/analyse_missings.rds")

#'4th Grade Math

missings_df1 <- analyse_missings(df1)
missings_df1 <- missings_df1[order(missings_df1$Omitted_Invalid),]
head(missings_df1)
tail(missings_df1)
round(mean(missings_df1[,3]),3)
round(sd(missings_df1[,3]), 3)
nrow(missings_df1)

#'------------------------------------------------------------------------------
#'
#'8th Grade Math

missings_df2 <- analyse_missings(df2)
missings_df2 <- missings_df2[order(missings_df2$Omitted_Invalid),]
head(missings_df2)
tail(missings_df2)
round(mean(missings_df2[,3]),3)
round(sd(missings_df2[,3]), 3)
nrow(missings_df2)

#'------------------------------------------------------------------------------
#'
#'4th Grade Science

missings_df3 <- analyse_missings(df3)
missings_df3 <- missings_df3[order(missings_df3$Omitted_Invalid),]
head(missings_df3)
tail(missings_df3)
round(mean(missings_df3[,3]),3)
round(sd(missings_df3[,3]), 3)
nrow(missings_df3)

#'------------------------------------------------------------------------------
#'
#'8th Grade Science

missings_df4 <- analyse_missings(df4)
missings_df4 <- missings_df4[order(missings_df4$Omitted_Invalid),]
head(missings_df4)
tail(missings_df4)
round(mean(missings_df4[,3]),3)
round(sd(missings_df4[,3]), 3)
nrow(missings_df4)

#'------------------------------------------------------------------------------
#'
#' ### Conclusion
#' df1 (4th Grade Math) has the largest range of missings between countries, 
#' the largest M and the largest SD of item omission proportions between countries. 
#' However, for model parsimony reasons, df4 (Grade 8 Science) is chosen, since the 8th grade subsets
#' encompass fewer countries and df4 displays the largest variability out of those.
#' 

#'------------------------------------------------------------------------------
#'
#' ### References
#' 
#' Fishbein, B., Taneva, M., & Kowolik, K. (2025). TIMSS 2023 User Guide for the International Database. Boston College, TIMSS & PIRLS International Study Center. https://timss2023.org/data
#' 








